export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" =
  "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILURE: "GET_INGREDIENTS_FAILURE" =
  "GET_INGREDIENTS_FAILURE";

export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT: "REMOVE_INGREDIENT" = "REMOVE_INGREDIENT";
export const UPDATE_INGREDIENTS: "UPDATE_INGREDIENTS" = "UPDATE_INGREDIENTS";

export const CLEAR_SELECTED_INGREDIENTS: "CLEAR_SELECTED_INGREDIENTS" =
  "CLEAR_SELECTED_INGREDIENTS";

export const INCREASE_COUNT: "INCREASE_COUNT" = "INCREASE_COUNT";
export const DECREASE_COUNT: "DECREASE_COUNT" = "DECREASE_COUNT";
