export const CHECKOUT_ORDER_REQUEST: "CHECKOUT_ORDER_REQUEST" =
  "CHECKOUT_ORDER_REQUEST";
export const CHECKOUT_ORDER_SUCCESS: "CHECKOUT_ORDER_SUCCESS" =
  "CHECKOUT_ORDER_SUCCESS";
export const CHECKOUT_ORDER_FAILURE: "CHECKOUT_ORDER_FAILURE" =
  "CHECKOUT_ORDER_FAILURE";
